print('Welcome to the tip calculator!')
total_bill = float(input('What was the total bill? $'))
tip_size = int(input('How much tip would you like to give? 10, 12, or 15? '))
total_people = int(input('How many people to split the bill?'))
tips = total_bill * (tip_size / 100)
result = round((total_bill + tips) / total_people, 2)
print(f'Each person shoud pay: ${result}')
